export const FINANCE_CHECK_ALLOWED_EXTENSIONS = ['.xlsx'] as const
export const FINANCE_CHECK_MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024
export const FINANCE_CHECK_TOLERANCE = 0.00001
export const FINANCE_CHECK_ROW_CONCURRENCY = 5
